name = "blucket"
main = "src/index.js"
compatibility_date = "2023-05-12"
compatibility_flags = [ "nodejs_compat" ]

# Production environment.
[env.production]
name = "blucket-production"
# Configure this to your own account.
account_id = "3648328bb7b24838c70d601e79891d98"
# Configure this to your own domain.
route = "blucket.alex1883.workers.dev"

[[env.production.r2_buckets]]
binding = 'r2_bucket'
bucket_name = 'r2-bucket-production'

[[env.production.vars]]
# 4 MiB, in bytes.
MAX_BLOCK_SIZE=4194304

# Staging environment.
[env.staging]
name = "blucket-staging"
# Configure this to your own account.
account_id = "3648328bb7b24838c70d601e79891d98"
# Configure this to your own domain.
route = "blucket-staging.alex1883.workers.dev"

[[env.staging.r2_buckets]]
binding = 'r2_bucket'
bucket_name = 'r2-bucket-staging'

[[env.staging.vars]]
# 4 MiB, in bytes.
MAX_BLOCK_SIZE=4194304

[env.dev]
name = "blucket-dev"

[[env.dev.r2_buckets]]
binding = 'r2_bucket'
bucket_name = 'r2-bucket-dev'
preview_bucket_name = 'r2-bucket-dev-preview'

[[env.dev.vars]]
# 4 MiB, in bytes.
MAX_BLOCK_SIZE=4194304

